language: php
dist: xenial
php:
    - '7.3'

cache:
    directories:
        - vendor
        - $HOME/.composer/cache/files

before_install:
    - phpenv config-rm xdebug.ini

install:
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install

script:
    - ./vendor/bin/phpcs --standard=.cs/cs_ruleset.xml --extensions=php bundle tests


notifications:
    email: false
