services:
    novaezsiteaccessfactory.ezadminui.component.stylesheets:
         parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
         public: false
         arguments:
            $template: "@@ezdesign/ezadminui/stylesheets.html.twig"
         tags:
             - { name: ezplatform.admin_ui.component, group: 'stylesheet-head' }

    novaezsiteaccessfactory.ezadminui.component.javascripts:
         parent: EzSystems\EzPlatformAdminUi\Component\TwigComponent
         public: false
         arguments:
             $template: "@@ezdesign/ezadminui/javascripts.html.twig"
         tags:
             - { name: ezplatform.admin_ui.component, group: 'script-body' }

    Novactive\Bundle\eZSiteAccessFactoryBundle\Listener\AdminTopMenu:
        arguments: ['@eZ\Publish\API\Repository\PermissionResolver']
        tags:
            - { name: kernel.event_listener, event: "ezplatform_admin_ui.menu_configure.main_menu", method: "onMenuConfigure",  priority: -100 }

