services:
    ibexa.adminui.novaezsiteaccessfactory.css_page:
        parent: Ibexa\AdminUi\Component\LinkComponent
        arguments:
            $href: "/bundles/novaezsiteaccessfactory/css/novaezsiteaccessfactory.css"
        tags:
            - { name: ibexa.admin_ui.component, group: 'stylesheet-head' }

    ibexa.adminui.novaezsiteaccessfactory.doc_js:
        parent: Ibexa\AdminUi\Component\ScriptComponent
        autowire: true
        autoconfigure: false
        public: false
        arguments:
            $src: "/bundles/novaezsiteaccessfactory/js/modules/doc.js"
        tags:
            - { name: ibexa.admin_ui.component, group: 'script-body' }

    ibexa.adminui.novaezsiteaccessfactory.form_js:
        parent: Ibexa\AdminUi\Component\ScriptComponent
        autowire: true
        autoconfigure: false
        public: false
        arguments:
            $src: "/bundles/novaezsiteaccessfactory/js/modules/editForms.js"
        tags:
            - { name: ibexa.admin_ui.component, group: 'script-body' }

    ibexa.adminui.novaezsiteaccessfactory.novaezsiteaccessfactory_js:
        parent: Ibexa\AdminUi\Component\ScriptComponent
        autowire: true
        autoconfigure: false
        public: false
        arguments:
            $src: "/bundles/novaezsiteaccessfactory/js/novaezsiteaccessfactory.js"
        tags:
            - { name: ibexa.admin_ui.component, group: 'script-body' }

    Novactive\Bundle\eZSiteAccessFactoryBundle\Listener\AdminTopMenu:
        arguments: ['@Ibexa\Contracts\Core\Repository\PermissionResolver']
        tags:
            - { name: kernel.event_listener, event: "ezplatform_admin_ui.menu_configure.main_menu", method: "onMenuConfigure",  priority: -100 }

