services:
    _defaults:
        autowire: true
        autoconfigure: false
        public: false

    Novactive\Bundle\eZSiteAccessFactoryBundle\Listener\EzUserLink:
        tags: ['doctrine.orm.entity_listener']

    Novactive\Bundle\eZSiteAccessFactoryBundle\Listener\EzRootLocationLink:
        tags: ['doctrine.orm.entity_listener']

